name: Update Playlist in Folder

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Create folder and download playlist
        run: |
          # Полностью очищаем и создаем папку заново
          rm -rf bormanulik
          mkdir -p bormanulik
          
          # Скачиваем файл в папку
          curl -L "https://raw.githubusercontent.com/bormanulik/TV/main/list.m3u" -o bormanulik/list.m3u
          
          # Проверяем результат
          if [ -s "bormanulik/list.m3u" ]; then
            echo "✅ File downloaded successfully to bormanulik/list.m3u"
            echo "File size: $(wc -c < bormanulik/list.m3u) bytes"
            ls -la bormanulik/
          else
            echo "❌ Downloaded file is empty or not created"
            exit 1
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add bormanulik/list.m3u
          
          if ! git diff --quiet && ! git diff --staged --quiet; then
            git commit -m "Update bormanulik/list.m3u playlist"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            echo "✅ Changes pushed successfully"
          else
            echo "ℹ️ No changes to commit"
          fi
