name: Update Playlist with GitHub CLI

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download playlist
        run: |
          rm -rf bormanulik
          mkdir -p bormanulik
          curl -L "https://raw.githubusercontent.com/bormanulik/TV/main/list.m3u" -o bormanulik/list.m3u
          echo "✅ File downloaded successfully"

      - name: Commit and push with GitHub CLI
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add bormanulik/list.m3u
          git commit -m "Update bormanulik playlist"
          gh auth setup-git
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
