name: Update Playlist

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download playlists
        run: |
          # Очистка и создание директорий
          rm -rf autoIPTV
          mkdir -p autoIPTV/bormanulik
          mkdir -p autoIPTV/IPTVSHARED
          mkdir -p autoIPTV/MaximKiselev
          mkdir -p autoIPTV/LoganetXIPTV
          mkdir -p autoIPTV/maks-mk
          mkdir -p autoIPTV/Spirt007
          mkdir -p autoIPTV/Dimonovich
          
          # Скачивание bormanulik playlist
          curl -L "https://raw.githubusercontent.com/bormanulik/TV/main/list.m3u" -o autoIPTV/bormanulik/list.m3u
          
          # Скачивание IPTVSHARED playlist, IPTV, TOPPEHT_TB, MEDIASHARED
          curl -L "https://raw.githubusercontent.com/IPTVSHARED/iptv/main/IPTV_SHARED.m3u" -o autoIPTV/IPTVSHARED/IPTV_SHARED.m3u  
          curl -L "https://raw.githubusercontent.com/IPTVSHARED/iptv/main/TOPPEHT_TB.m3u" -o autoIPTV/IPTVSHARED/TOPPEHT_TB.m3u          
          curl -L "https://raw.githubusercontent.com/IPTVSHARED/iptv/main/MEDIASHARED.m3u" -o autoIPTV/IPTVSHARED/MEDIASHARED.m3u
          
          # Скачивание MaximKiselev playlist
          curl -L "https://raw.githubusercontent.com/MaximKiselev/iptv/main/playlist.m3u" -o autoIPTV/MaximKiselev/playlist.m3u
          
          # Скачивание LoganetXIPTV playlists
          curl -L "https://raw.githubusercontent.com/blackbirdstudiorus/LoganetXIPTV/main/LoganetXAll.m3u" -o autoIPTV/LoganetXIPTV/LoganetXAll.m3u
          curl -L "https://raw.githubusercontent.com/blackbirdstudiorus/LoganetXIPTV/main/LoganetXStrawberry.m3u" -o autoIPTV/LoganetXIPTV/LoganetXStrawberry.m3u
          
          # Скачивание maks-mk playlists
          curl -L "https://raw.githubusercontent.com/maks-mk/lampatv/main/adult2.m3u8" -o autoIPTV/maks-mk/adult2.m3u8
          curl -L "https://raw.githubusercontent.com/maks-mk/lampatv/main/kino18-dubl.m3u" -o autoIPTV/maks-mk/kino18-dubl.m3u
          
          # Скачивание Spirt007 playlist
          curl -L "https://raw.githubusercontent.com/Spirt007/Tvru/Master/Rus.m3u" -o autoIPTV/Spirt007/Rus.m3u

          # Скачивание Dimonovich playlist Android TV + Free TV + FILMS
          curl -L "https://raw.githubusercontent.com/Dimonovich/TV/Dimonovich/FREE/TV" -o autoIPTV/Dimonovich/TV.m3u
          curl -L "https://raw.githubusercontent.com/Dimonovich/TV/Dimonovich/FREE/FILMS" -o autoIPTV/Dimonovich/FILMS.m3u
          curl -L "https://raw.githubusercontent.com/Dimonovich/TV/Dimonovich/FREE/.m3u" -o autoIPTV/Dimonovich/1.m3u
          
          echo "✅ All files downloaded"

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add autoIPTV/**
          git commit -m "Update playlists" || echo "No changes to commit"
          git push
