name: Test Create bormanulik

on:
  workflow_dispatch:

jobs:
  test-create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create directory and file
        run: |
          rm -rf bormanulik
          mkdir -p bormanulik
          echo "# Test M3U file" > bormanulik/list.m3u
          ls -la bormanulik/

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Test: Create bormanulik/list.m3u" || echo "No changes to commit"
          git push
