name: Update list.m3u

on:
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test download
        run: |
          rm -rf bormanulik
          mkdir -p bormanulik
          curl -v -L -o bormanulik/list.m3u https://raw.githubusercontent.com/bormanulik/TV/main/list.m3u
          ls -la bormanulik/
