name: Diagnostic Test

on:
  workflow_dispatch:

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check repository status
        run: |
          echo "Current directory:"
          pwd
          echo "Files in repository:"
          ls -la
          echo "Git status:"
          git status

      - name: Test file creation
        run: |
          echo "Testing file creation..."
          echo "# Test file created at $(date)" > test_file.txt
          ls -la test_file.txt

      - name: Test curl
        run: |
          echo "Testing curl..."
          curl -L -o test_download.txt https://raw.githubusercontent.com/bormanulik/TV/main/list.m3u
          echo "Download result:"
          ls -la test_download.txt
          echo "File size:"
          wc -l test_download.txt

      - name: Try to commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add test_file.txt test_download.txt
          git commit -m "Diagnostic test files" || echo "Nothing to commit"
          git push || echo "Push failed"
