name: Working Update Playlist

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download playlist
        run: |
          # Простое скачивание
          curl -L "https://raw.githubusercontent.com/bormanulik/TV/main/list.m3u" -o current_playlist.m3u
          
          # Проверим, что файл не пустой
          if [ -s "current_playlist.m3u" ]; then
            echo "✅ File downloaded successfully"
            echo "File size: $(wc -c < current_playlist.m3u) bytes"
          else
            echo "❌ Downloaded file is empty"
            exit 1
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Добавляем файл
          git add current_playlist.m3u
          
          # Проверяем, есть ли изменения
          if git diff --quiet && git diff --staged --quiet; then
            echo "ℹ️ No changes to commit"
          else
            git commit -m "Update playlist from bormanulik"
            git push
            echo "✅ Changes pushed successfully"
          fi
