name: Debug bormanulik update

on:
  workflow_dispatch:

jobs:
  debug-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Debug current structure
        run: |
          echo "Current directory structure:"
          ls -la
          echo "bormanulik content (if exists):"
          ls -la bormanulik/ 2>/dev/null || echo "bormanulik folder not found"

      - name: Create/update file
        run: |
          mkdir -p bormanulik
          curl -L -v -o bormanulik/list.m3u https://raw.githubusercontent.com/bormanulik/TV/main/list.m3u
          echo "Download result:"
          ls -la bormanulik/

      - name: Setup git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push
        run: |
          git add bormanulik/list.m3u
          if ! git diff --quiet && ! git diff --staged --quiet; then
            git commit -m "Update bormanulik/list.m3u"
            git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
            echo "Changes pushed successfully"
          else
            echo "No changes to commit"
          fi
        continue-on-error: true
