name: Update simple list.m3u

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download M3U file
        run: |
          curl -L -o list_bormanulik.m3u https://raw.githubusercontent.com/bormanulik/TV/main/list.m3u
          echo "File size:"
          ls -la list_bormanulik.m3u

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add list_bormanulik.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update list_bormanulik.m3u" && git push)
