name: Working Update Playlist

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Download playlist
        run: |
          curl -L "https://raw.githubusercontent.com/bormanulik/TV/main/list.m3u" -o current_playlist.m3u
          
          if [ -s "current_playlist.m3u" ]; then
            echo "✅ File downloaded successfully"
            echo "File size: $(wc -c < current_playlist.m3u) bytes"
          else
            echo "❌ Downloaded file is empty"
            exit 1
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add current_playlist.m3u
          
          if ! git diff --quiet && ! git diff --staged --quiet; then
            git commit -m "Update playlist from bormanulik"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            echo "✅ Changes pushed successfully"
          else
            echo "ℹ️ No changes to commit"
          fi
