# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ pkgs,modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # =============================
  # 🧠 ZRAM — вместо SWAP на SSD
  # =============================
  zramSwap.enable = true;
  zramSwap.algorithm = "lz4";
  zramSwap.memoryPercent = 50;

#  boot = {
    # kernelPackages = pkgs.linuxPackages_cachyos;

    # blacklistedKernelModules = [ "radeon" ];
#    kernelModules = [
#      "amdgpu"
#      "kvm-amd"
#    ];

#    extraModulePackages = [ ];
#    kernelParams = [
#      "amd_pstate=activ"
#      "amdgpu.gpu_recovery=1"
#      "mem_sleep_default=deep"
#      "pcie_aspm.policy=powersupersave"
      # "amdgpu.sg_display=0"
#      "amdgpu.dcdebugmask=0x10"
      # "amdgpu.ppfeaturemask=0xffffffff"
#      "video=eDP-1:1920x1200@60.00100"
#      "initcall_blacklist=acpi_cpufreq_init"
#    ];

#     loader = {
#       efi.canTouchEfiVariables = true;
#       systemd-boot = {
#         enable = true;
#         configurationLimit = 10;
#       };
#     };

#    initrd = {
#      systemd.enable = true;

#      availableKernelModules = [
#        "nvme"
#        "xhci_pci"
#        "thunderbolt"
#        "usbhid"
#        "sdhci_pci"
#        "usb_storage"
#        "sd_mod"
#      ];

      #kernelModules = [ "amdgpu" ];
#    };

#  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/53306dda-9384-442b-a68f-7e5fe56f7b80";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5871-3CBA";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

#  fileSystems."/home" = {
#    device = "/dev/disk/by-uuid/596377c5-9a9a-4086-8736-347a06b0e45b";
#    fsType = "ext4";
#  };

#  boot.initrd.luks.devices."luks-f0a4330d-1e0b-4f31-9653-162851182efb".device =
#    "/dev/disk/by-uuid/f0a4330d-1e0b-4f31-9653-162851182efb";

   swapDevices = [ {
    device = "/dev/disk/by-uuid/91358c34-5df0-4fa7-af73-a6ac6e5880ef";
  } ];

  services = {
    fstrim = {
      enable = true;
      interval = "weekly";
    };
    udisks2 = {
      enable = true;
      mountOnMedia = true;
    };

  };

}
